"""empty message

Revision ID: 6dc7cbae2f83
Revises: 42b068d08c7a
Create Date: 2025-10-10 11:21:24.707620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc7cbae2f83'
down_revision: Union[str, Sequence[str], None] = '42b068d08c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('moderator_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('announcements', 'moderator_message')
    # ### end Alembic commands ###
