"""empty message

Revision ID: c83933f1c4b8
Revises: a41c106153bd
Create Date: 2025-09-30 07:22:47.839556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83933f1c4b8'
down_revision: Union[str, Sequence[str], None] = 'a41c106153bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fandoms',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fandoms_name'), 'fandoms', ['name'], unique=True)
    op.create_table('nsfw_fetishes',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nsfw_fetishes_name'), 'nsfw_fetishes', ['name'], unique=True)
    op.create_table('nsfw_taboo',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nsfw_taboo_name'), 'nsfw_taboo', ['name'], unique=True)
    op.create_table('tags',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('announcements',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('orientation', sa.String(length=8), nullable=True),
    sa.Column('gender', sa.String(length=7), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('is_crossgender', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_anonymously', sa.Boolean(), nullable=False),
    sa.Column('is_verify', sa.Boolean(), nullable=False),
    sa.Column('is_nsfw', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annnouncements_fandoms',
    sa.Column('annnouncement_id', sa.UUID(), nullable=False),
    sa.Column('fandom_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['annnouncement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['fandom_id'], ['fandoms.id'], ),
    sa.PrimaryKeyConstraint('annnouncement_id', 'fandom_id')
    )
    op.create_table('annnouncements_nsfw_fetishes',
    sa.Column('annnouncement_id', sa.UUID(), nullable=False),
    sa.Column('nsfw_fetish_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['annnouncement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['nsfw_fetish_id'], ['nsfw_fetishes.id'], ),
    sa.PrimaryKeyConstraint('annnouncement_id', 'nsfw_fetish_id')
    )
    op.create_table('annnouncements_nsfw_taboo',
    sa.Column('annnouncement_id', sa.UUID(), nullable=False),
    sa.Column('nsfw_taboo_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['annnouncement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['nsfw_taboo_id'], ['nsfw_taboo.id'], ),
    sa.PrimaryKeyConstraint('annnouncement_id', 'nsfw_taboo_id')
    )
    op.create_table('annnouncements_tags',
    sa.Column('annnouncement_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['annnouncement_id'], ['announcements.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('annnouncement_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annnouncements_tags')
    op.drop_table('annnouncements_nsfw_taboo')
    op.drop_table('annnouncements_nsfw_fetishes')
    op.drop_table('annnouncements_fandoms')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_nsfw_taboo_name'), table_name='nsfw_taboo')
    op.drop_table('nsfw_taboo')
    op.drop_index(op.f('ix_nsfw_fetishes_name'), table_name='nsfw_fetishes')
    op.drop_table('nsfw_fetishes')
    op.drop_index(op.f('ix_fandoms_name'), table_name='fandoms')
    op.drop_table('fandoms')
    # ### end Alembic commands ###
